# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu 
menu:
- page: 首页
  url: /
  icon: 
- page: 区块链
  url: /categories/区块链/
  icon: 
- page: 矿池
  url: /categories/矿池/
  icon: 
- page: 钱包
  url: /categories/钱包/
  icon: 
- page: 资源
  url: /categories/资源/
  icon: 

## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - search
  - social
  - category
  - archive
  - tagcloud

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>主题Snippet v1.2.0版本已经上线！欢迎更新~ <br/>
            主题下载：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet主题</a> <br/>
            <hr/>接受贡献，包括不限于提交问题与需求，修复代码。欢迎Pull Request<br/>支持主题：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star一下</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/xingyunbite
 - name: 邮箱
   icon: envelope-o
   href: xingyunbite@foxmail.com

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:

# 主题自定义个性化配置

## 网站宣传语
branding: 星云比特 区块链技术博客

## 设置banner背景图片
banner:
    img:

## 缩略图自定义随机图片
defaultImgs:
  - 

## 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme: 

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="http://xingyunbite.github.io" target="_blank">xingyunbite</a>


## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: true
  uyan_id: 2158688

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid: cyt8KmUC1
  conf: prod_855a68d3b3d91855360a6215672a505a

## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics: 1272924949

### 百度统计
baidu_analytics: 

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 

### 百度文章推送
baidu_push:

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
